config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'

  get '/games', to: 'games#index'
  get 'games/new', to: 'games#new'
  get 'games/:id', to: 'games#show'
  post 'games', to: 'games#create'
  delete 'games/:id', to: 'games#destroy'

  post '/players', to: 'players#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game

  before_create do |player|
    player.turn = Player.where(game_id: player.game_id).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    render :index
  end

  def create
    gameurl = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
    game = Game.create(gameurl: gameurl)
    host = Player.create(name: params["player"]["name"], turn: 0, currency: 3, game: game)

    redirect_to :action => "show", :id => game.gameurl
  end

  def show
    @game = Game.find_by(gameurl: params[:id])
    @host = Player.find_by(game_id: @game.id)
    @current_players = Player.where(game_id: @game.id)

    # On click of button, increment to next player
    # @player_turn = Game.current_player

    def your_turn
      @current_player = @host.name
      

    end

    # i = 0
    # while i < @current_players.length
    #     @current_turn = @current_players[i]
    #     i += 1
    # end

    # @current_turn = @current_players[i]
    # @next_turn = @current_turn[i + 1]
    # player.turn = Player.where(game_id: player.game_id).count

    render :show
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout false

  def create
    player_name = params["player_name"]
    game_id = params["game_id"]
    puts player_name

    new_player = Player.create(name: player_name, game_id: game_id, currency: 3)
    # TODO add the respond value
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Let's play LCR</h1>

<%= form_with scope: :player, url: games_path do |form| %>
  <%= form.text_field :name, placeholder: "Name" %>
  <%= submit_tag("Let's Play") %>
<% end %>

app/views/games/show.html.erb
<h1>Welcome to LRC</h1>

<!-- <form action="/players" method="post">
  <label>Your name</label>
  <input type="text" name="player_name" placeholder="Priyanka Chopra" required>
  <input type="hidden" name="game_id" value="<#%= @game.id %>">
  <button type="submit">Add Player</button>
</form> -->


<h2>Game Information</h2>
<%= link_to "Next turn", games_path(game_id: @game.id), class: "next_player", remote: true %>

<ul>
  <li>Game ID: <%= @game.id %></li>
  <li>Round: </li>
  <li>Pot Total: </li>
  <li> Turn: <%#= @current_turn.name %> </li>
</ul>

<br><br>

<h2>Player Information</h2>
<%= form_tag(players_path, :method => "post") do %>
  <%= label_tag(:player_name, "Add player:") %>
  <%= text_field_tag(:player_name, nil, placeholder: 'Priyanka Chopra') %>
  <%= hidden_field_tag(:game_id, "#{@game.id}") %>
  <%= submit_tag("Join the Game") %>
<% end %>

<ol>
  <% @current_players.each do |player| %>
  <li>
    <strong><%= player.name %></strong> /
    Order: <%= player.turn %> /
    Dollars: <%= player.currency %> /
    Last Roll:
  </li>
  <% end %>
</ol>

<br><br>

<h2>Roll</h2>
<%= link_to "Next Roll", games_path(game_id: @game.id), class: "next_roll", remote: true %>
<ul>
  <li>L</li>
  <li>R</li>
  <li>C</li>
</ul>

<!-- Keep record of:

For Games:
• Game session (id)
• Center Pot total
• Turn (player name?)
• Round (integer)

For Players:
• Players (in game session)
• Current Player (pre current player)
• Player wallet / currency
• Player dice count
• Roll (per player, per turn)
• Player Before (Name - post current player)
• Player After (Name - post current player)
• Player Before (update currency based on role)
• Player After (update currency based on role) -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Threedotsashot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>